name: weather_app_clean_architecture
description: "weather app with clean architecture, di, bloc for state management"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  dartz: ^0.10.1
  http: ^1.6.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900

